/**
 * FIREBASE SYNC LAYER
 * ------------------------------------------------------------
 * Implements the locked Session Lobby System: a short session code
 * generated by one player, joined by up to 4 others, synced live via
 * Firebase Realtime Database.
 *
 * This file is the ONLY place that talks to Firebase directly. Every
 * other file (main.js, trust.js, etc.) calls the small API exposed
 * at the bottom — Session.create(), Session.join(), Session.onUpdate(),
 * Session.setPlayerData(), etc. — and never touches `firebase` itself.
 * ------------------------------------------------------------
 */

const firebaseConfig = {
  apiKey: "-",
  authDomain: "butterfly-of-the-forgotten.firebaseapp.com",
  databaseURL: "https://butterfly-of-the-forgotten-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "butterfly-of-the-forgotten",
  storageBucket: "butterfly-of-the-forgotten.firebasestorage.app",
  messagingSenderId: "277184033301",
  appId: "1:277184033301:web:ea9e8a15e0d15f3aa9d41c",
  measurementId: "G-9QYZSNLRJ0"
};

const Session = (() => {
  let db = null;
  let sessionRef = null;
  let sessionCode = null;
  let playerId = null;
  let isReady = false;

  /**
   * Loads the Firebase SDK from CDN at runtime, since this project has
   * no build step / npm bundler — index.html stays plain script tags.
   */
  function _loadSDK() {
    return new Promise((resolve, reject) => {
      if (window.firebase) {
        resolve();
        return;
      }
      const appScript = document.createElement('script');
      appScript.src = 'https://www.gstatic.com/firebasejs/9.23.0/firebase-app-compat.js';
      appScript.onload = () => {
        const dbScript = document.createElement('script');
        dbScript.src = 'https://www.gstatic.com/firebasejs/9.23.0/firebase-database-compat.js';
        dbScript.onload = resolve;
        dbScript.onerror = reject;
        document.head.appendChild(dbScript);
      };
      appScript.onerror = reject;
      document.head.appendChild(appScript);
    });
  }

  async function init() {
    if (isReady) return;
    await _loadSDK();
    firebase.initializeApp(firebaseConfig);
    db = firebase.database();
    isReady = true;
  }

  function _generateCode() {
    // Short, readable, academy-themed feel (no 0/O/1/I to avoid confusion)
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    let code = '';
    for (let i = 0; i < 5; i++) {
      code += chars[Math.floor(Math.random() * chars.length)];
    }
    return code;
  }

  function _generatePlayerId() {
    return 'p_' + Math.random().toString(36).slice(2, 10);
  }

  /**
   * Creates a brand new session and returns its code.
   * The creating player is automatically added as player 1.
   */
  async function create() {
    await init();
    sessionCode = _generateCode();
    playerId = _generatePlayerId();
    sessionRef = db.ref('sessions/' + sessionCode);

    await sessionRef.set({
      createdAt: Date.now(),
      trust: 60,
      players: {
        [playerId]: {
          joinedAt: Date.now(),
          name: null,
          sanity: 75,
          role: null,
          connected: true
        }
      }
    });

    _attachPresence();
    return sessionCode;
  }

  /**
   * Joins an existing session by code. Returns false if the session
   * doesn't exist or is already full (5 players, per locked design).
   */
  async function join(code) {
    await init();
    const cleanCode = code.trim().toUpperCase();
    const ref = db.ref('sessions/' + cleanCode);
    const snapshot = await ref.once('value');

    if (!snapshot.exists()) {
      return { ok: false, reason: 'not_found' };
    }

    const data = snapshot.val();
    const currentPlayers = data.players ? Object.keys(data.players).length : 0;
    if (currentPlayers >= 5) {
      return { ok: false, reason: 'full' };
    }

    sessionCode = cleanCode;
    playerId = _generatePlayerId();
    sessionRef = ref;

    await sessionRef.child('players/' + playerId).set({
      joinedAt: Date.now(),
      name: null,
      sanity: 75,
      role: null,
      connected: true
    });

    _attachPresence();
    return { ok: true };
  }

  /**
   * Marks this player as disconnected if their browser closes/loses
   * connection, per the locked Player Absence System (Tier 2). Firebase's
   * onDisconnect handles this even on a hard crash, not just a clean exit.
   */
  function _attachPresence() {
    if (!sessionRef || !playerId) return;
    const playerRef = sessionRef.child('players/' + playerId);
    playerRef.child('connected').onDisconnect().set(false);
  }

  function getCode() {
    return sessionCode;
  }

  function getPlayerId() {
    return playerId;
  }

  /**
   * Subscribes to live session updates. callback receives the full
   * session object every time anything changes (player joins, sanity
   * shifts, trust shifts, etc.) — simple full-replace sync, fine for
   * a 5-player session size.
   */
  function onUpdate(callback) {
    if (!sessionRef) return;
    sessionRef.on('value', snapshot => {
      callback(snapshot.val());
    });
  }

  function setPlayerData(partial) {
    if (!sessionRef || !playerId) return Promise.resolve();
    return sessionRef.child('players/' + playerId).update(partial);
  }

  function shiftTrust(delta) {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child('trust').transaction(current => {
      const value = (current === null ? 60 : current) + delta;
      return Math.max(0, Math.min(100, value));
    });
  }

  async function getPlayerCount() {
    if (!sessionRef) return 0;
    const snapshot = await sessionRef.child('players').once('value');
    return snapshot.exists() ? Object.keys(snapshot.val()).length : 0;
  }

  return {
    create,
    join,
    getCode,
    getPlayerId,
    onUpdate,
    setPlayerData,
    shiftTrust,
    getPlayerCount
  };
})();
