/**
 * FIREBASE SYNC LAYER
 * ------------------------------------------------------------
 * Implements the locked Session Lobby System: a short session code
 * generated by one player, joined by up to 4 others, synced live via
 * Firebase Realtime Database.
 *
 * This file is the ONLY place that talks to Firebase directly. Every
 * other file (main.js, trust.js, etc.) calls the small API exposed
 * at the bottom — Session.create(), Session.join(), Session.onUpdate(),
 * Session.setPlayerData(), etc. — and never touches `firebase` itself.
 * ------------------------------------------------------------
 */

const firebaseConfig = {
  apiKey: "AIzaSyDkSIwzVhFrXnLUCfDzIStMmTtO4B97iac",
  authDomain: "butterfly-of-the-forgotten.firebaseapp.com",
  databaseURL: "https://butterfly-of-the-forgotten-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "butterfly-of-the-forgotten",
  storageBucket: "butterfly-of-the-forgotten.firebasestorage.app",
  messagingSenderId: "277184033301",
  appId: "1:277184033301:web:ea9e8a15e0d15f3aa9d41c",
  measurementId: "G-9QYZSNLRJ0"
};

const Session = (() => {
  let db = null;
  let sessionRef = null;
  let sessionCode = null;
  let playerId = null;
  let isReady = false;

  /**
   * Loads the Firebase SDK from CDN at runtime, since this project has
   * no build step / npm bundler — index.html stays plain script tags.
   */
  function _loadSDK() {
    return new Promise((resolve, reject) => {
      if (window.firebase) {
        resolve();
        return;
      }
      const appScript = document.createElement('script');
      appScript.src = 'https://www.gstatic.com/firebasejs/9.23.0/firebase-app-compat.js';
      appScript.onload = () => {
        const dbScript = document.createElement('script');
        dbScript.src = 'https://www.gstatic.com/firebasejs/9.23.0/firebase-database-compat.js';
        dbScript.onload = resolve;
        dbScript.onerror = reject;
        document.head.appendChild(dbScript);
      };
      appScript.onerror = reject;
      document.head.appendChild(appScript);
    });
  }

  async function init() {
    if (isReady) return;
    await _loadSDK();
    firebase.initializeApp(firebaseConfig);
    db = firebase.database();
    isReady = true;
  }

  function _generateCode() {
    // Short, readable, academy-themed feel (no 0/O/1/I to avoid confusion)
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    let code = '';
    for (let i = 0; i < 5; i++) {
      code += chars[Math.floor(Math.random() * chars.length)];
    }
    return code;
  }

  function _generatePlayerId() {
    return 'p_' + Math.random().toString(36).slice(2, 10);
  }

  /**
   * Creates a brand new session and returns its code.
   * The creating player is automatically added as player 1.
   */
  async function create() {
    await init();
    sessionCode = _generateCode();
    playerId = _generatePlayerId();
    sessionRef = db.ref('sessions/' + sessionCode);

    await sessionRef.set({
      createdAt: Date.now(),
      trust: 60,
      players: {
        [playerId]: {
          joinedAt: Date.now(),
          name: null,
          sanity: 75,
          role: null,
          connected: true
        }
      }
    });

    _attachPresence();
    return sessionCode;
  }

  /**
   * Joins an existing session by code using an atomic transaction to
   * prevent race conditions when multiple players join simultaneously.
   */
  async function join(code) {
    await init();
    const cleanCode = code.trim().toUpperCase();
    const ref = db.ref('sessions/' + cleanCode);
    const snapshot = await ref.once('value');

    if (!snapshot.exists()) {
      return { ok: false, reason: 'not_found' };
    }

    const data = snapshot.val();

    // Block joining a session that already started
    if (data.started) {
      return { ok: false, reason: 'started' };
    }

    // Use a transaction on the players node to atomically check + add,
    // preventing two players from both passing the count check simultaneously
    sessionCode = cleanCode;
    playerId = _generatePlayerId();
    sessionRef = ref;

    let joinResult = { ok: false, reason: 'full' };

    await ref.child('players').transaction(players => {
      const currentCount = players ? Object.keys(players).length : 0;
      if (currentCount >= 5) return; // abort transaction = full
      const newPlayers = players || {};
      newPlayers[playerId] = {
        joinedAt: Date.now(),
        name: null,
        sanity: 75,
        role: null,
        connected: true
      };
      joinResult = { ok: true };
      return newPlayers;
    });

    if (!joinResult.ok) return joinResult;

    _attachPresence();
    return { ok: true };
  }

  /**
   * Marks this player as disconnected if their browser closes/loses
   * connection, per the locked Player Absence System (Tier 2). Firebase's
   * onDisconnect handles this even on a hard crash, not just a clean exit.
   */
  function _attachPresence() {
    if (!sessionRef || !playerId) return;
    const playerRef = sessionRef.child('players/' + playerId);
    playerRef.child('connected').onDisconnect().set(false);
  }

  function getCode() {
    return sessionCode;
  }

  function getPlayerId() {
    return playerId;
  }

  /**
   * Subscribes to live session updates. callback receives the full
   * session object every time anything changes (player joins, sanity
   * shifts, trust shifts, etc.) — simple full-replace sync, fine for
   * a 5-player session size.
   */
  function onUpdate(callback) {
    if (!sessionRef) return;
    sessionRef.on('value', snapshot => {
      callback(snapshot.val());
    });
  }

  function setPlayerData(partial) {
    if (!sessionRef || !playerId) return Promise.resolve();
    return sessionRef.child('players/' + playerId).update(partial);
  }

  function shiftTrust(delta) {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child('trust').transaction(current => {
      const value = (current === null ? 60 : current) + delta;
      return Math.max(0, Math.min(100, value));
    });
  }

  /**
   * Marks the session as started so latecomers can't join mid-game.
   * Called by beginSynchronizedEntry() once all 5 are present.
   */
  function markStarted() {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child('started').set(true);
  }

  /**
   * OBSERVER DECISION — writes the Observer's final-gate choice so every
   * other player computes the same shared ending. Routed through the
   * Session API (not a bare firebase.database() call from main.js) to
   * keep this file the only one that talks to Firebase directly.
   */
  function submitObserverChoice(choice) {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child('observerChoice').set(choice);
  }

  /**
   * Waits for the Observer's choice to actually appear, instead of reading
   * once after a fixed delay (which could read null if the Observer was
   * still deciding). Falls back to whatever's there after timeoutMs so a
   * slow/dropped Observer doesn't hang the other players forever.
   */
  function waitForObserverChoice(timeoutMs = 15000) {
    if (!sessionRef) return Promise.resolve(null);
    return new Promise(resolve => {
      const ref = sessionRef.child('observerChoice');
      let done = false;
      let timer = null;

      const finish = (val) => {
        if (done) return;
        done = true;
        ref.off('value', handler);
        if (timer) clearTimeout(timer);
        resolve(val || null);
      };

      const handler = snap => {
        const val = snap.val();
        if (val) finish(val);
      };

      ref.on('value', handler);
      timer = setTimeout(() => {
        ref.once('value').then(snap => finish(snap.val()));
      }, timeoutMs);
    });
  }

  /**
   * One-time full read of the session — used by the host to see the
   * current player list before computing role assignments.
   */
  async function getSession() {
    if (!sessionRef) return null;
    const snap = await sessionRef.once('value');
    return snap.val();
  }

  /**
   * Host-only: writes a role for every player at once.
   */
  function assignRoles(roleByPlayerId) {
    if (!sessionRef) return Promise.resolve();
    const updates = {};
    Object.entries(roleByPlayerId).forEach(([pid, role]) => {
      updates[`players/${pid}/role`] = role;
    });
    return sessionRef.update(updates);
  }

  /**
   * Waits for THIS player's own role to actually appear, instead of
   * reading once after a fixed delay (which could read null if the
   * host was still writing the assignment).
   */
  function waitForOwnRole(timeoutMs = 8000) {
    if (!sessionRef || !playerId) return Promise.resolve(null);
    return new Promise(resolve => {
      const ref = sessionRef.child(`players/${playerId}/role`);
      let done = false;
      let timer = null;

      const finish = (val) => {
        if (done) return;
        done = true;
        ref.off('value', handler);
        if (timer) clearTimeout(timer);
        resolve(val || null);
      };

      const handler = snap => {
        const val = snap.val();
        if (val) finish(val);
      };

      ref.on('value', handler);
      timer = setTimeout(() => {
        ref.once('value').then(snap => finish(snap.val()));
      }, timeoutMs);
    });
  }

  async function getPlayerCount() {
    if (!sessionRef) return 0;
    const snapshot = await sessionRef.child('players').once('value');
    return snapshot.exists() ? Object.keys(snapshot.val()).length : 0;
  }

  /**
   * Removes this player from the session (fix for stale Firebase entries
   * on restart/reload). Also cancels the onDisconnect handler so it
   * doesn't fire redundantly after we've already cleaned up manually.
   */
  async function leave() {
    if (!sessionRef || !playerId) return;
    try {
      const playerRef = sessionRef.child('players/' + playerId);
      await playerRef.child('connected').onDisconnect().cancel();
      await playerRef.remove();
    } catch (e) {
      // best-effort cleanup — fine if this fails (e.g. connection already gone)
    }
  }

  /**
   * CONVERGENCE REAL VOTING — writes this player's actual shared-question
   * answer (not just a submitted flag) so majority can be computed from
   * real Firebase data instead of a simulated/random group.
   */
  function submitAnswer(roomId, answer) {
    if (!sessionRef || !playerId) return Promise.resolve();
    return sessionRef.child(`answers/${roomId}/${playerId}`).set(answer);
  }

  /**
   * Waits until `expectedCount` players have answered, or until timeoutMs
   * elapses (in case someone disconnected mid-vote) — then resolves with
   * whatever answers are present.
   */
  function waitForAnswers(roomId, expectedCount, timeoutMs = 8000) {
    if (!sessionRef) return Promise.resolve([]);
    return new Promise(resolve => {
      const ref = sessionRef.child(`answers/${roomId}`);
      let done = false;
      let timer = null;

      const finish = (val) => {
        if (done) return;
        done = true;
        ref.off('value', handler);
        if (timer) clearTimeout(timer);
        resolve(val ? Object.values(val) : []);
      };

      const handler = snap => {
        const val = snap.val();
        const count = val ? Object.keys(val).length : 0;
        if (count >= expectedCount) finish(val);
      };

      ref.on('value', handler);
      timer = setTimeout(() => {
        ref.once('value').then(snap => finish(snap.val()));
      }, timeoutMs);
    });
  }

  /**
   * Plant Doubt — Betrayer writes a poisoned option label to Firebase.
   * Other players read this before their choice renders and see the
   * altered text. Betrayer always sees the real option text.
   */
  function plantDoubt(roomId, optionIndex, alteredText) {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child(`plantDoubt/${roomId}`).set({
      optionIndex,
      alteredText,
      by: playerId
    });
  }

  function getPlantDoubt(roomId) {
    if (!sessionRef) return Promise.resolve(null);
    return sessionRef.child(`plantDoubt/${roomId}`).once('value')
      .then(snap => snap.val());
  }

  /**
   * Borrowed Memory — Forgotten reads one fragment of shared session state.
   * Returns an object with { type, value } or null if nothing available.
   */
  async function borrowMemory() {
    if (!sessionRef) return null;
    const snap = await sessionRef.once('value');
    const session = snap.val();
    if (!session || !session.players) return null;

    const fragments = [];
    const players = Object.entries(session.players).filter(([id]) => id !== playerId);

    // Fragment 1: a random other player's sanity tier
    if (players.length > 0) {
      const [, p] = players[Math.floor(Math.random() * players.length)];
      const sanity = p.sanity || 75;
      const tier = sanity >= 60 ? 'Stable' : sanity >= 30 ? 'Distorted' : 'Lost';
      fragments.push({ type: 'sanity', value: `Someone among you is ${tier}.` });
    }

    // Fragment 2: whether Plant Doubt was used this room
    const currentRoom = GameState.loadState('player')?.currentScene || '';
    const doubt = session.plantDoubt?.[currentRoom];
    if (doubt) {
      fragments.push({ type: 'betrayer', value: 'Something was changed before anyone voted.' });
    } else {
      fragments.push({ type: 'betrayer', value: 'Nothing has been altered. Yet.' });
    }

    // Fragment 3: Observer truth fragment if available
    if (session.observerTruth) {
      fragments.push({ type: 'observer', value: `The Observer saw: "${session.observerTruth}"` });
    }

    return fragments[Math.floor(Math.random() * fragments.length)];
  }

  /**
   * OBSERVER TALLY — writes this player's vote submission flag so
   * Observer can read how many have submitted (not what they chose).
   */
  function submitVote(roomId) {
    if (!sessionRef || !playerId) return Promise.resolve();
    return sessionRef.child(`votes/${roomId}/${playerId}`).set(true);
  }

  function getVoteCount(roomId) {
    if (!sessionRef) return Promise.resolve(0);
    return sessionRef.child(`votes/${roomId}`).once('value')
      .then(snap => snap.exists() ? Object.keys(snap.val()).length : 0);
  }

  function onVoteUpdate(roomId, callback) {
    if (!sessionRef) return () => {};
    const ref = sessionRef.child(`votes/${roomId}`);
    ref.on('value', snap => {
      callback(snap.exists() ? Object.keys(snap.val()).length : 0);
    });
    return () => ref.off('value');
  }

  /**
   * WANDERER GROUP CHECK — writes a check request to the session.
   * All players are notified; anyone who was Plant Doubted sees a private
   * "your last choice may have been altered" message.
   */
  function requestGroupCheck(roomId) {
    if (!sessionRef || !playerId) return Promise.resolve();
    return sessionRef.child(`groupCheck/${roomId}`).set({
      requestedBy: playerId,
      timestamp: Date.now()
    });
  }

  function onGroupCheck(roomId, callback) {
    if (!sessionRef) return () => {};
    const ref = sessionRef.child(`groupCheck/${roomId}`);
    ref.on('value', snap => { if (snap.exists()) callback(snap.val()); });
    return () => ref.off('value');
  }

  /**
   * FORGOTTEN ANONYMOUS SHARE — pushes a fragment into a shared
   * "academy message" path visible to all players briefly.
   * Source player ID is never written — truly anonymous.
   */
  function shareFragment(text) {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child('sharedFragment').set({
      text,
      timestamp: Date.now()
    });
  }

  function onSharedFragment(callback) {
    if (!sessionRef) return () => {};
    const ref = sessionRef.child('sharedFragment');
    ref.on('value', snap => { if (snap.exists()) callback(snap.val()); });
    return () => ref.off('value');
  }

  /**
   * BETRAYER DISPUTE — anonymously disputes the last group decision,
   * nudging trust. Source is never written.
   */
  function disputeResult(roomId) {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child(`dispute/${roomId}`).set({
      timestamp: Date.now()
    });
  }

  function onDispute(roomId, callback) {
    if (!sessionRef) return () => {};
    const ref = sessionRef.child(`dispute/${roomId}`);
    ref.on('value', snap => { if (snap.exists()) callback(); });
    return () => ref.off('value');
  }

  return {
    create,
    join,
    getCode,
    getPlayerId,
    onUpdate,
    setPlayerData,
    shiftTrust,
    markStarted,
    plantDoubt,
    getPlantDoubt,
    borrowMemory,
    getPlayerCount,
    submitVote,
    getVoteCount,
    onVoteUpdate,
    requestGroupCheck,
    onGroupCheck,
    shareFragment,
    onSharedFragment,
    disputeResult,
    onDispute,
    leave,
    submitAnswer,
    waitForAnswers,
    submitObserverChoice,
    waitForObserverChoice,
    getSession,
    assignRoles,
    waitForOwnRole
  };
})();
