/**
 * FIREBASE SYNC LAYER
 * ------------------------------------------------------------
 * Implements the locked Session Lobby System: a short session code
 * generated by one player, joined by up to 4 others, synced live via
 * Firebase Realtime Database.
 *
 * This file is the ONLY place that talks to Firebase directly. Every
 * other file (main.js, trust.js, etc.) calls the small API exposed
 * at the bottom — Session.create(), Session.join(), Session.onUpdate(),
 * Session.setPlayerData(), etc. — and never touches `firebase` itself.
 * ------------------------------------------------------------
 */

const firebaseConfig = {
  apiKey: "AIzaSyDkSIwzVhFrXnLUCfDzIStMmTtO4B97iac",
  authDomain: "butterfly-of-the-forgotten.firebaseapp.com",
  databaseURL: "https://butterfly-of-the-forgotten-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "butterfly-of-the-forgotten",
  storageBucket: "butterfly-of-the-forgotten.firebasestorage.app",
  messagingSenderId: "277184033301",
  appId: "1:277184033301:web:ea9e8a15e0d15f3aa9d41c",
  measurementId: "G-9QYZSNLRJ0"
};

const Session = (() => {
  let db = null;
  let sessionRef = null;
  let sessionCode = null;
  let playerId = null;
  let isReady = false;

  /**
   * Loads the Firebase SDK from CDN at runtime, since this project has
   * no build step / npm bundler — index.html stays plain script tags.
   */
  function _loadSDK() {
    return new Promise((resolve, reject) => {
      if (window.firebase) {
        resolve();
        return;
      }
      const appScript = document.createElement('script');
      appScript.src = 'https://www.gstatic.com/firebasejs/9.23.0/firebase-app-compat.js';
      appScript.onload = () => {
        const dbScript = document.createElement('script');
        dbScript.src = 'https://www.gstatic.com/firebasejs/9.23.0/firebase-database-compat.js';
        dbScript.onload = resolve;
        dbScript.onerror = reject;
        document.head.appendChild(dbScript);
      };
      appScript.onerror = reject;
      document.head.appendChild(appScript);
    });
  }

  async function init() {
    if (isReady) return;
    await _loadSDK();
    firebase.initializeApp(firebaseConfig);
    db = firebase.database();
    isReady = true;
  }

  function _generateCode() {
    // Short, readable, academy-themed feel (no 0/O/1/I to avoid confusion)
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    let code = '';
    for (let i = 0; i < 5; i++) {
      code += chars[Math.floor(Math.random() * chars.length)];
    }
    return code;
  }

  function _generatePlayerId() {
    return 'p_' + Math.random().toString(36).slice(2, 10);
  }

  /**
   * Creates a brand new session and returns its code.
   * The creating player is automatically added as player 1.
   */
  async function create() {
    await init();
    sessionCode = _generateCode();
    playerId = _generatePlayerId();
    sessionRef = db.ref('sessions/' + sessionCode);

    await sessionRef.set({
      createdAt: Date.now(),
      trust: 60,
      players: {
        [playerId]: {
          joinedAt: Date.now(),
          name: null,
          sanity: 75,
          role: null,
          connected: true
        }
      }
    });

    _attachPresence();
    return sessionCode;
  }

  /**
   * Joins an existing session by code using an atomic transaction to
   * prevent race conditions when multiple players join simultaneously.
   */
  async function join(code) {
    await init();
    const cleanCode = code.trim().toUpperCase();
    const ref = db.ref('sessions/' + cleanCode);
    const snapshot = await ref.once('value');

    if (!snapshot.exists()) {
      return { ok: false, reason: 'not_found' };
    }

    const data = snapshot.val();

    // Block joining a session that already started
    if (data.started) {
      return { ok: false, reason: 'started' };
    }

    // Use a transaction on the players node to atomically check + add,
    // preventing two players from both passing the count check simultaneously
    sessionCode = cleanCode;
    playerId = _generatePlayerId();
    sessionRef = ref;

    let joinResult = { ok: false, reason: 'full' };

    await ref.child('players').transaction(players => {
      const currentCount = players ? Object.keys(players).length : 0;
      if (currentCount >= 5) return; // abort transaction = full
      const newPlayers = players || {};
      newPlayers[playerId] = {
        joinedAt: Date.now(),
        name: null,
        sanity: 75,
        role: null,
        connected: true
      };
      joinResult = { ok: true };
      return newPlayers;
    });

    if (!joinResult.ok) return joinResult;

    _attachPresence();
    return { ok: true };
  }

  /**
   * Marks this player as disconnected if their browser closes/loses
   * connection, per the locked Player Absence System (Tier 2). Firebase's
   * onDisconnect handles this even on a hard crash, not just a clean exit.
   */
  function _attachPresence() {
    if (!sessionRef || !playerId) return;
    const playerRef = sessionRef.child('players/' + playerId);
    playerRef.child('connected').onDisconnect().set(false);
  }

  function getCode() {
    return sessionCode;
  }

  function getPlayerId() {
    return playerId;
  }

  /**
   * Subscribes to live session updates. callback receives the full
   * session object every time anything changes (player joins, sanity
   * shifts, trust shifts, etc.) — simple full-replace sync, fine for
   * a 5-player session size.
   */
  function onUpdate(callback) {
    if (!sessionRef) return;
    sessionRef.on('value', snapshot => {
      callback(snapshot.val());
    });
  }

  function setPlayerData(partial) {
    if (!sessionRef || !playerId) return Promise.resolve();
    return sessionRef.child('players/' + playerId).update(partial);
  }

  function shiftTrust(delta) {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child('trust').transaction(current => {
      const value = (current === null ? 60 : current) + delta;
      return Math.max(0, Math.min(100, value));
    });
  }

  /**
   * Marks the session as started so latecomers can't join mid-game.
   * Called by beginSynchronizedEntry() once all 5 are present.
   */
  function markStarted() {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child('started').set(true);
  }

  async function getPlayerCount() {
    if (!sessionRef) return 0;
    const snapshot = await sessionRef.child('players').once('value');
    return snapshot.exists() ? Object.keys(snapshot.val()).length : 0;
  }

  /**
   * Plant Doubt — Betrayer writes a poisoned option label to Firebase.
   * Other players read this before their choice renders and see the
   * altered text. Betrayer always sees the real option text.
   */
  function plantDoubt(roomId, optionIndex, alteredText) {
    if (!sessionRef) return Promise.resolve();
    return sessionRef.child(`plantDoubt/${roomId}`).set({
      optionIndex,
      alteredText,
      by: playerId
    });
  }

  function getPlantDoubt(roomId) {
    if (!sessionRef) return Promise.resolve(null);
    return sessionRef.child(`plantDoubt/${roomId}`).once('value')
      .then(snap => snap.val());
  }

  /**
   * Borrowed Memory — Forgotten reads one fragment of shared session state.
   * Returns an object with { type, value } or null if nothing available.
   */
  async function borrowMemory() {
    if (!sessionRef) return null;
    const snap = await sessionRef.once('value');
    const session = snap.val();
    if (!session || !session.players) return null;

    const fragments = [];
    const players = Object.entries(session.players).filter(([id]) => id !== playerId);

    // Fragment 1: a random other player's sanity tier
    if (players.length > 0) {
      const [, p] = players[Math.floor(Math.random() * players.length)];
      const sanity = p.sanity || 75;
      const tier = sanity >= 60 ? 'Stable' : sanity >= 30 ? 'Distorted' : 'Lost';
      fragments.push({ type: 'sanity', value: `Someone among you is ${tier}.` });
    }

    // Fragment 2: whether Plant Doubt was used this room
    const currentRoom = GameState.loadState('player')?.currentScene || '';
    const doubt = session.plantDoubt?.[currentRoom];
    if (doubt) {
      fragments.push({ type: 'betrayer', value: 'Something was changed before anyone voted.' });
    } else {
      fragments.push({ type: 'betrayer', value: 'Nothing has been altered. Yet.' });
    }

    // Fragment 3: Observer truth fragment if available
    if (session.observerTruth) {
      fragments.push({ type: 'observer', value: `The Observer saw: "${session.observerTruth}"` });
    }

    return fragments[Math.floor(Math.random() * fragments.length)];
  }

  return {
    create,
    join,
    getCode,
    getPlayerId,
    onUpdate,
    setPlayerData,
    shiftTrust,
    markStarted,
    plantDoubt,
    getPlantDoubt,
    borrowMemory,
    getPlayerCount
  };
})();
